# Generated by Django 3.0.7 on 2023-06-03 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentmanagementsystem', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentDetails',
        ),
    ]
