# Generated by Django 3.0.7 on 2023-06-03 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentmanagementsystem', '0003_auto_20230603_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cgpa', models.IntegerField()),
                ('gpa1', models.IntegerField()),
                ('gpa2', models.IntegerField()),
                ('gpa3', models.IntegerField()),
                ('gpa4', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentmanagementsystem.Student')),
            ],
        ),
    ]
