# Generated by Django 3.0.7 on 2023-06-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentmanagementsystem', '0004_grades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='gpa2',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='grades',
            name='gpa3',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='grades',
            name='gpa4',
            field=models.FloatField(),
        ),
    ]
