# Generated by Django 3.0.7 on 2023-06-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentmanagementsystem', '0005_auto_20230603_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='cgpa',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='grades',
            name='gpa1',
            field=models.FloatField(),
        ),
    ]
