# Generated by Django 4.2.1 on 2023-06-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentmanagementsystem', '0006_auto_20230603_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
