# Generated by Django 5.2 on 2025-04-14 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentmanagementsystem', '0012_rename_fees_ammount_to_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fees',
            old_name='amount',
            new_name='ammount',
        ),
    ]
