# Generated by Django 5.2 on 2025-04-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentmanagementsystem', '0014_alter_student_department_alter_student_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='venue',
            field=models.CharField(max_length=100),
        ),
    ]
