# Generated by Django 5.2 on 2025-04-21 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentmanagementsystem', '0015_alter_examination_venue'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRecommendation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('entry_salary', models.CharField(max_length=100)),
                ('experienced_salary', models.CharField(max_length=100)),
                ('job_website', models.URLField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentmanagementsystem.courses')),
            ],
        ),
    ]
